### ISSUE TITLE
 "virtualgps.py", line 117,

### ISSUE THREAD

**Issue by socuellamino** [rkaczorek/virtualgps#11]
I get this error when try to run the py

Traceback (most recent call last):
  File "virtualgps.py", line 117, in <module>
    raise KeyboardInterrupt
KeyboardInterrupt

meaybe need to config first? how do it? and wich format

i try this  sudo python3 virtualgps.py --lat 42.617736 --lon -3.718675 --el 700 --profile victor --config /etc/virtualgps.conf --nmea /etc/virtualgps.log

thanks

**Comment by AnonymousWebHacker** [comment]
Me too, error 117

**Comment by AnonymousWebHacker** [comment]
```
python3 virtualgps.py 
sudo: aa-complain: orden no encontrada
Streaming virtual location (Lat: 0, Lon: 0, El: 0) to serial GPS device /dev/pts/1
Traceback (most recent call last):
  File "/tmp/virtualgps_test/virtualgps.py", line 152, in <module>
    if latitude > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by rkaczorek** [comment]
Now you're running it without any parameters i.e. no config and no command line arguments for latitude, longitude and elevation. Obviously this is not what you want.
Anyway I have just added default values for this situation. Expected behavior: If no config file nor command line arguments are specified, latitude, longitude and elevation are set to default = 0.
